### PR TITLE
Fix selected exports

### PR DESCRIPTION
**Pull request by thejonan**
Errors due to empty filter when the export is in selected substancs mode

### CODE REVIEW

**Review by vedina — CHANGES_REQUESTED** [review]
materials information report now works with selected entries , but some of the other reports do not
- "study results - all values, minimal information" returns xslx file without data
- "study report - new format (experimental)" -returns only partially filled file (missing study data)
- "Nanoreg physchem template" - returns xlsx file without data

**Comment by thejonan** [comment]
It looks like a problem with post-query pre-processing issue. For some queries it _does_ return empty reports, even with unfilled templates. For example, if only `NNRG-2cb3446e-c9c4-24f2-4519-e06fa3aacb50` substance is selected, the resulting report is totally unfilled, and it has references to `response.rows`, which aren't to be found in the actual SOLR response.

In other occasions, with _new format (experimental)_ report, for example, some cells remain unfilled, like `F2` (`{{ A2 | study | document_uuid_s }}`) `template-material-study.xls`.

For other sets of substances, there isn't such a problem. I even tried having selected all of the filtered results, and the getting reports in both ways - the responses are identical.

Generally, I've tested that the responses in both ways - selection or filtering, have identical structure, which means the problem isn't in the "selected" vs "filtered", but in the data pre-processing.

**Comment by vedina** [comment]
> It looks like a problem with post-query pre-processing issue. For some queries it _does_ return empty reports, even with unfilled templates. For example, if only `NNRG-2cb3446e-c9c4-24f2-4519-e06fa3aacb50` substance is selected, the resulting report is totally unfilled, and it has references to `response.rows`, which aren't to be found in the actual SOLR response.
> 
> In other occasions, with _new format (experimental)_ report, for example, some cells remain unfilled, like `F2` (`{{ A2 | study | document_uuid_s }}`) `template-material-study.xls`.
> 
> For other sets of substances, there isn't such a problem. I even tried having selected all of the filtered results, and the getting reports in both ways - the responses are identical.
> 
> Generally, I've tested that the responses in both ways - selection or filtering, have identical structure, which means the problem isn't in the "selected" vs "filtered", but in the data pre-processing.
> 
> ### Example 1
> The `Ag @ IIT` substance - when selected alone. The request is:
> 
> ```
> {
> 	"params": {
> 		"fq": ["s_uuid_hs:(NNRG-2cb3446e-c9c4-24f2-4519-e06fa3aacb50)"],
> 		"echoParams": "none",
> 		"rows": 999998,
> 		"fl": ["*,[child parentFilter=type_s:substance childFilter=\"type_s:params OR type_s:conditions\" limit=10000]"],
> 		"facet": "false"
> 	}
> }
> ```
> 
> The response (beginning) is:
> 
> ```
> {
>     "responseHeader": {
>         "zkConnected": true,
>         "status": 0,
>         "QTime": 5
>     },
>     "response": {
>         "numFound": 1,
>         "start": 0,
>         "docs": [
>             {
>                 "content_hss": [
>                     "IIT"
>                 ],
>                 "dbtag_hss": [
>                     "NNRG"
>                 ],
>                 "name_hs": "Ag 20 nm",
>                 "publicname_hs": "Ag @ IIT",
>                 "owner_name_hs": "NANoREG",
>                 "substanceType_hs": "NPO_1892",
>                 "s_uuid_hs": "NNRG-2cb3446e-c9c4-24f2-4519-e06fa3aacb50",
>                 "type_s": "substance",
>                 "SUMMARY.RESULTS_hss": [
>                     "P-CHEM.CRYSTALLINE_PHASE_SECTION",
>                     "P-CHEM.SURFACE_CHEMISTRY_SECTION",
>                     "P-CHEM.PC_GRANULOMETRY_SECTION"
>                 ],
>                 "SUMMARY.REFS_hss": [
>                     "Provided",
>                     "Ag_NPs_IIT_WAXD",
>                     "Ag_NPs_IIT_SAXS",
>                     "AG @ IIT"
>                 ],
>                 "SUMMARY.REFOWNERS_hss": [
>                     "IIT"
>                 ],
>                 "id": "ca9a707f-fca3-4065-b280-7539b15cb69b",
>                 "_version_": 1671821632143884300,
>                 "_childDocuments_": [
>                     {
>                         "Dispersion protocol_s": "IC protocol",
>                         "Vial_s": "Ag NPs IIT",
>                         "document_uuid_s": "NRDM-00000000-0000-0000-0000-00000000002f",
>                         "endpointcategory_s": "PC_GRANULOMETRY_SECTION",
>                         "guidance_s": "WAXS",
>                         "id": "NRDM-00000000-0000-0000-0000-00000000002f/1816/prm",
>                         "topcategory_s": "P-CHEM",
>                         "type_s": "params",
>                         "_version_": 1671821632143884300
>                     },
>                     {
>                         "DATA_GATHERING_INSTRUMENTS_s": "WAXS",
>                         "document_uuid_s": "NRDM-00000000-0000-0000-0000-00000000002f",
>                         "effectid_hs": "NRDM-00000000-0000-0000-0000-00000000002f/1816",
>                         "endpointcategory_s": "PC_GRANULOMETRY_SECTION",
>                         "guidance_s": "WAXS",
>                         "id": "NRDM-00000000-0000-0000-0000-00000000002f/1816/cn",
>                         "size_measurement_s": "Core Size Distribution - Diameter",
>                         "size_measurement_type_s": "Monomodal",
>                         "topcategory_s": "P-CHEM",
>                         "type_s": "conditions",
>                         "_version_": 1671821632143884300
>                     },
> 
> ...
> ```

Here the problem is that the response does not contain any records of type_s:study, hence the postprocessing returns empty `rows=[]` .    So the problem is not in the processing, but the query.  Hence the query should be fixed, but where/how ?

**Comment by vedina** [comment]
it seems to me the problem with 'selected` exports is as follows.  
- In the `filtered` case, we have `filter-escaped` , which includes in the childDocuments the records of type study, which match the filter. 

```
value: "*,[child parentFilter=type_s:substance childFilter=\"({{filter-escaped}}) OR type_s:params OR type_s:conditions\" limit=10000]"
```
- In the `selected` case, and if no widget from the left panel is selected , this filter is not be set at all and the query looks like this
```
0: "*,[child parentFilter=type_s:substance childFilter="type_s:params OR type_s:conditions" limit=10000]"
```

Hence, no study types are returned and the post-processing (which relies on study records existence) returns empty arrays.

- In the `selected` case, and if some widgets at left are selected , this filter will look like (if project NANoREG is selected)

```
*,[child parentFilter=type_s:substance childFilter="(owner_name_s:NANoREG) OR type_s:params OR type_s:conditions" limit=10000]
```
and the report will be generated correctly.

- The dependence of the "selected" export on the filter is something not entirely expected.  For example one can add a "selected substance"  while filtering for project X (or some other filter), and then change the filter to project Y (or another filter) , while the "selected substance" will stay selected; but the export will fail as there will be no study records matching the second filter.

**Comment by thejonan** [comment]
With a bunch of head scratching and refactoring so that `Exporting` can handle more complex behaviour - the fix should be OK now.

**Review by vedina — APPROVED** [review]

**Pull request merged**
