### PR TITLE
Migrate studies, composition and substance kits

### PR DESCRIPTION
**Pull request by thejonan**
Big change, including:
- Transferred all DataTable management tools from old jToxKit to the new one
- Migrated ToxStudy, ToxSubstance and ToxComposition to the new jToxKit
- Migrated dataTables to the newest official release.

### CODE REVIEW

**Comment by thejonan** [comment]
@vedina - this one got rebased and fixed to work again. Please, verify that.

Using 11ty setup, the study kit can be accessed in this manner: `http://localhost:8081/projects/nanoreg/study/?substanceUri=NNRG-2cb3446e-c9c4-24f2-4519-e06fa3aacb50`.

**Comment by vedina** [comment]
tests at jToxKit/tests/index.html fail  with 
```
TypeError: a$ is not a function
```

**Comment by vedina** [comment]
Are there examples like we had before https://github.com/ideaconsult/Toxtree.js/tree/master/uses ?

**Comment by vedina** [comment]
please check the migrated study work smoothly with study configurations from the old version .  At the moment this error is thrown and the configuration is ignored

```
jtox-kit.kits.js:179 Uncaught TypeError: Cannot read property 'composition' of undefined
    at CompositionKit.prepareTable (jtox-kit.kits.js:179)
    at CompositionKit.<anonymous> (jtox-kit.kits.js:276)
    at Object.fireCallback (jtox-kit.js:185)
    at Object.success (jtox-kit.widgets.js:1451)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```

**Comment by vedina** [comment]
confirmed the configuration works nicely

One more question - could we specify `data-base-url`  as URL parameter as well?  In the 11ty setup there are multiple AMBIT instances .

**Comment by thejonan** [comment]
> One more question - could we specify `data-base-url` as URL parameter as well? In the 11ty setup there are multiple AMBIT instances .

Yes - every parameter can be specified in either of three ways:
- as URL parameter
- as a variable in the provided configuration
- as a `data-XXX` attribute of the root element.

The priority should be in that order (URL parameter being the highest).

**Comment by vedina** [comment]
> > One more question - could we specify `data-base-url` as URL parameter as well? In the 11ty setup there are multiple AMBIT instances .
> 
> Yes - every parameter can be specified in either of three ways:
> 
> * as URL parameter
> * as a variable in the provided configuration
> * as a `data-XXX` attribute of the root element.
> 
> The priority should be in that order (URL parameter being the highest).

need some help - can't get any of the `base-url` spellings to work

**Pull request merged**
